authority-portal.config.api-key=${AP_CONFIG_API_KEY}
authority-portal.invitation.expiration=43200
authority-portal.caas.sovity.limit-per-organization=1
authority-portal.caas.sovity.url=http://localhost:8080
authority-portal.base-url=http://localhost

# Test Environment Configuration (required)
authority-portal.deployment.environments.test.title=Test Environment
authority-portal.deployment.environments.test.position=0

# Test Environment Data Catalog Settings
authority-portal.deployment.environments.test.data-catalog.dataspace-names.default=TestDataspace
authority-portal.deployment.environments.test.data-catalog.hide-offline-data-offers-after=15m
authority-portal.deployment.environments.test.data-catalog.catalog-page-page-size=10

# Test Environment DAPS Configuration
authority-portal.deployment.environments.test.daps.url=http://keycloak:8080
authority-portal.deployment.environments.test.daps.realm-name=authority-portal
authority-portal.deployment.environments.test.daps.client-id=authority-portal-client
authority-portal.deployment.environments.test.daps.client-secret=${AP_CLIENT_SECRET}